### ISSUE TITLE
something wrong with your cmake .. creation

### ISSUE THREAD

**Issue by SonySandy** [AudioMorphology/Europi#1]
On running make it gives an error/home/pi/raspi2fb/raspi2fb.c:43:25: fatal error: bsd/libutil.h: No such file or directory.  #unclude <bsd/libutil.h>

**Comment by AudioMorphology** [comment]
This sounds like an issue with raspi2fb rather than Europi, so can I suggest you check the build instructions on Andrew's github page:

https://github.com/AndrewFromMelbourne/raspi2fb.git
